config/routes.rb
require "multidomain"
Confer::Application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations" }

  constraints(Multidomain) do
    scope module: "project" do
      resources :participants do
        member do
          put :approve
        end
      end
      resources :reports do
        member do
          put :approve
        end
      end
      resources :materials, only: [:index, :new, :create, :destroy] do
        member do
          put :approve
        end
      end

      resources :organizers, only: [:index, :new, :destroy, :create]
      resources :feedbacks, only: [:index, :show, :destroy, :create]

      resources :news_articles, path: "news"
      match '/feed' => 'news_items#feed',
        as: :feed,
        defaults: { format: 'atom' }

      resources :conferences, only: [:edit, :update]
      resources :pages, except: [:show]

      get "/settings" => "conferences#edit", as: :settings
      get "/contacts" => "feedbacks#new", as: :contacts

      get "/" => "projects#index"
      get "/:id" => "pages#show", as: :public_page
    end
  end

  namespace :admin do
    resources :users do
      resources :logs, only: [:index]
      member do
        put :make_admin
        put :make_user
        put :confirm
      end
    end
    resources :conferences do
      resources :logs, only: [:index]
      member do
        put :approve
      end
    end
    get "logs" => "logs#index", as: :logs
  end

  resources :users
  resources :conferences

  get "/about" => "main#about", as: :about
  root :to => 'main#index'
end

app/models/participant.rb
# == Schema Information
#
# Table name: participants
#
#  id            :integer          not null, primary key
#  user_id       :integer
#  conference_id :integer
#  state         :string(255)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Participant < ActiveRecord::Base
  ## included modules & attr_*
  attr_accessible :conference_id, :state, :user_id, :reports_attributes

  ## associations
  belongs_to :user
  belongs_to :conference
  has_many :reports, dependent: :destroy
  accepts_nested_attributes_for :reports, :reject_if => proc { |attributes| attributes['description'].blank? || attributes["title"].blank? }

  ## plugins
  audited

  state_machine :initial => :new do
    event :approve do
      transition :new => :approved
    end
    after_transition :new => :approved, :do => :notify_user
  end

  ## callbacks

  ## validations
  validates :user_id, presence: true
  validates :conference_id, presence: true

  ## named_scopes

  ## class methods

  public
  protected
  private

    def notify_user
      ConferenceMailer.participation_approved(conference, user).deliver
    end
end

app/controllers/participants_controller.rb
class ParticipantsController < BaseProjectController
  load_and_authorize_resource

  def index
    @organizers = @conference.organizers
    @approved_participants = @conference.participants.with_state(:approved)
    @pending_participants = @conference.participants.with_state(:new)
    if can? :moderate, @conference
      render "index_admin"
    else
      render "index"
    end
  end

  def new
    @participant = Participant.new
    @participant.reports.build
  end

  def create
    attrs = params[:participant].dup
    attrs[:conference_id] = @conference.id
    attrs[:reports_attributes]["0"][:conference_id] = @conference.id
    current_user.participations.create!(attrs)
    redirect_to conference_site_url(@conference), notice: t('projects.participant.request_send')
  end

  def destroy
    Participant.find(params[:id]).destroy
    redirect_to participants_path, notice: t('projects.participants.destroyed')
  end

  def approve
    Participant.find(params[:id]).approve!
    redirect_to participants_path, notice: t('projects.participants.approved')
    authorize! :moderate, @conference
  end
end

app/controllers/project/base_project_controller.rb
class Project::BaseProjectController < ApplicationController
  layout "project"

  before_filter :preload_project
  before_filter :preload_participant, :preload_organizer
  before_filter :load_menu_pages
  helper_method :conference_site_url, :service_url

  private

    def service_url
      request.domain
    end

    def preload_project
      @conference = Conference.find_by_domain(request.subdomain)
    end

    def authorize_project_management
      authorize! :moderate, @conference
    end

    def check_if_organizer
      redirect_to conference_site_url(@conference), notice: t('projects.news.notices.become_organizer') if @current_organizer.nil?
    end

    def conference_site_url(conference)
      root_url(subdomain: conference.domain)
    end

    def preload_participant
      @current_participant = @conference.participants.where(user_id: current_user.id).last if signed_in?
    end

    def preload_organizer
      @current_organizer = @conference.organizers.where(user_id: current_user.id).last if signed_in?
    end

    def load_menu_pages
      @menu_pages = @conference.pages.in_menu
    end

end

app/controllers/project/conferences_controller.rb
class Project::ConferencesController < Project::BaseProjectController
  before_filter :authorize_project_management

  def edit
  end

  def update
    @conference = Conference.find(params[:id])
    if @conference.update_attributes(params[:conference])
      redirect_to settings_path, notice: t('projects.conferences.notices.updated')
    else
      render :edit
    end
  end

end

app/controllers/project/feedbacks_controller.rb
class Project::FeedbacksController < Project::BaseProjectController
  before_filter :authorize_project_management, except: [ :create, :new ]

  def index
    @feedbacks = @conference.feedbacks.order("id DESC")
  end

  def show
    @feedback = @conference.feedbacks.find(params[:id])
    @feedback.read! if @feedback.unread?
  end

  def new
    @feedback = Feedback.new
  end

  def create
    attrs = params[:feedback]
    attrs[:user_id] = current_user.id if signed_in?
    @feedback = @conference.feedbacks.create(attrs)
    if @feedback.valid?
      redirect_to contacts_path, notice: t('projects.feedbacks.notices.created')
    else
      render action: "new"
    end
  end

  def destroy
    @feedback = @conference.feedbacks.find(params[:id])
    @feedback.destroy
    redirect_to feedbacks_path, notice: t('projects.feedbacks.notices.removed')
  end
end

app/controllers/project/materials_controller.rb
class Project::MaterialsController < Project::BaseProjectController
  load_and_authorize_resource
  before_filter :preload_user_reports, only: [:new]

  def index
    @materials = Material.all
  end

  def new
    @material = Material.new
  end

  def create
    attrs = params[:material].dup
    attrs[:user_id] = current_user.id
    @material = @conference.materials.create(attrs)
    if @material.valid?
      redirect_to materials_path, notice: t('projects.materials.notices.created')
    else
      render :new
    end
  end

  def approve
    @material = Material.find(params[:id])
    @material.approve!
    redirect_to materials_path, notice: t('projects.materials.notices.approved')
  end

  def destroy
    @material = Material.find(params[:id])
    @material.destroy
    redirect_to materials_path, notice: t('projects.materials.notices.removed')
  end

  private

    def preload_user_reports
      if @current_organizer
        @reports = @conference.reports.with_state(:approved)
      elsif @current_participant
        @reports = @conference.reports.with_state(:approved).where(participant_id: @current_participant.id)
      else
        @reports = []
      end
    end
end

app/controllers/project/news_articles_controller.rb
class Project::NewsArticlesController < Project::BaseProjectController
  load_and_authorize_resource
  before_filter :check_if_organizer, only: [:create, :new]

  def index
    @news_articles = NewsArticle.where(conference_id: @conference.id)
    @title = "#{@conference.name}"
    @updated = @news_articles.first.updated_at unless @news_articles.empty?

    respond_to do |format|
      format.html
      format.atom { render layout: false }
      format.rss { redirect_to news_articles_path(format: :atom), status: :moved_permanently }
    end
  end

  def show
    @news_article = @conference.news_articles.where(id: params[:id]).last
    @page_title = @news_article.title
  end

  def new
    @news_article = NewsArticle.new
  end

  def create
    attrs = params[:news_article].dup
    attrs[:organizer_id] = @current_organizer.id
    @news_article = @conference.news_articles.create!(attrs)
    redirect_to news_article_path(@news_article), notice: t('projects.news.notices.created')
  end

  def edit
    @news_article = @conference.news_articles.where(id: params[:id]).last
  end

  def update
    @news_article = @conference.news_articles.where(id: params[:id]).last
    @news_article.update_attributes(params[:news_article])
    redirect_to news_article_path(@news_article), notice: t('projects.news.notices.updated')
  end

  def destroy
    @news_article = @conference.news_articles.where(id: params[:id]).last
    @news_article.destroy
    redirect_to news_articles_path, notice: t('projects.news.notices.destroyed')
  end
end

app/controllers/project/organizers_controller.rb
class Project::OrganizersController < Project::BaseProjectController
  before_filter :authorize_project_management

  def index
    @organizers = @conference.organizers
  end

  def new
    @organizer = Organizer.new
  end

  def destroy
    @conference.organizers.find(params[:id]).destroy
    redirect_to organizers_path, notice: t('projects.organizers.notices.destroyed')
  end

  def create
    @organizer = @conference.organizers.create!(params[:organizer])
    redirect_to organizers_path, notice: t('projects.organizers.notices.created')
  end
end

app/controllers/project/pages_controller.rb
class Project::PagesController < Project::BaseProjectController
  #load_and_authorize_resource
  before_filter :verify_access, except: [:show]

  def index
    @pages = @conference.pages
  end

  def new
    @page = @conference.pages.new
  end

  def create
    @page = @conference.pages.create(params[:page])

    if @page.valid?
      redirect_to pages_path, notice: t('projects.pages.notices.created')
    else
      render "new"
    end
  end

  def update
    @page = @conference.pages.find_by_permalink(params[:id])
    @page.update_attributes(params[:page])
    if @page.valid?
      redirect_to pages_path, notice: t('projects.pages.notices.updated')
    else
      render "edit"
    end
  end

  def edit
    @page = @conference.pages.find_by_permalink(params[:id])
  end

  def destroy
    @page = @conference.pages.find_by_permalink(params[:id])
    @page.destroy
    redirect_to pages_path, notice: t('projects.pages.notices.removed')
  end

  def show
    @page = @conference.pages.find_by_permalink(params[:id])
    @page_title = @page.title
  end

  private

    def verify_access
      authorize! :manage, Page
    end

end

app/controllers/project/participants_controller.rb
class Project::ParticipantsController < Project::BaseProjectController
  load_and_authorize_resource

  def index
    @organizers = @conference.organizers
    @approved_participants = @conference.participants.with_state(:approved)
    @pending_participants = @conference.participants.with_state(:new)
    if can? :moderate, @conference
      render "index_admin"
    else
      render "index"
    end
  end

  def new
    @participant = Participant.new
    @participant.reports.build
  end

  def create
    attrs = params[:participant].dup
    attrs[:conference_id] = @conference.id
    attrs[:reports_attributes]["0"][:conference_id] = @conference.id
    current_user.participations.create!(attrs)
    redirect_to conference_site_url(@conference), notice: t('projects.participant.request_send')
  end

  def destroy
    Participant.find(params[:id]).destroy
    redirect_to participants_path, notice: t('projects.participants.destroyed')
  end

  def approve
    Participant.find(params[:id]).approve!
    redirect_to participants_path, notice: t('projects.participants.approved')
    authorize! :moderate, @conference
  end
end

app/controllers/project/projects_controller.rb
class Project::ProjectsController < Project::BaseProjectController

  def index
    @page_title += " #{@conference.name}"
  end

  def settings
    
  end

end

app/controllers/project/reports_controller.rb
class Project::ReportsController < Project::BaseProjectController
  load_and_authorize_resource

  def index
    @reports = @conference.reports
    @pending_reports_count = @conference.reports.with_state(:pending).size
    if can? :moderate, @conference
      render "index_admin"
    else
      render "index"
    end
  end

  def edit
    @report = Report.find(params[:id])
  end

  def update
    @report = Report.find(params[:id])
    @report.update_attributes(params[:report])
    redirect_to edit_report_path(@report), notice: t('projects.reports.notices.updated')
  end

  def destroy
    Report.find(params[:id]).destroy
    redirect_to reports_path, notice: t('projects.reports.notices.removed')
  end

  def approve
    Report.find(params[:id]).approve!
    redirect_to reports_path, notice: t('projects.reports.notices.approved')
    authorize! :moderate, @conference
  end

end

app/controllers/project/users_controller.rb
class Project::UsersController < Project::BaseProjectController
  def index
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def project_link(subdomain)
    link_to subdomain, "http://#{subdomain}.#{request.host}"
  end
end

app/views/project/participants/_form.html.haml
%h3= t('projects.participant.form.title')
= semantic_form_for @participant do |f|
  %span.show-report-link= link_to t("projects.participant.form.show_report"), "#"
  .report_fields.hidden
    = f.semantic_fields_for :reports do |r|
      = r.input :title, label: t('projects.participant.form.report_title')
      = r.input :description, label: t('projects.participant.form.report_description')
  = f.actions do
    = f.action :submit, button_html: { class: "btn btn-success" }, label: t('projects.participant.form.take_part')

app/views/project/participants/_organizers.html.haml
%h4= "#{t('projects.participants.organizers')}:"
%ul.inline
  - @organizers.each do |org|
    %li= org.full_name

%br

app/views/project/participants/index.html.haml
.well
  %h1= t('projects.participants.index_title')
  %p= t('projects.participants.index_desc')

= render partial: "organizers"


%h4= "#{t('projects.participants.participants_list')}:"
%table.table.table-bordered.tablesorter.tablesorter-default
  %thead
    %tr
      %th= t('projects.participants.name')
      %th= t('projects.participants.address')
      %th= t('projects.participants.reports')
  - @approved_participants.each do |participant|
    %tr
      %td
        - unless participant.reports.empty?
          %span.label.label-info= t('projects.participants.is_speaker')
        = participant.user.full_name
      %td= participant.user.address
      %td
        - participant.reports.each do |report|
          = report.title

app/views/project/participants/index_admin.html.haml
.well
  %h1= t('projects.participants.index_title')
  %p= t('projects.participants.management')

= render partial: "organizers"

%h4= "#{t('projects.participants.participants_list')}:"
.b-participants__nav.admin
  %ul.nav.nav-tabs
    %li.pending.active
      - link_title = "#{t('projects.participants.nav.pending')}"
      - link_title += "(#{@pending_participants.size})" unless @pending_participants.empty?
      = link_to link_title, "#", class: "pending"
    %li.approved
      = link_to t('projects.participants.nav.approved'), "#", class: "approved"

- unless @pending_participants.empty?
  %table.table.table-bordered.tablesorter.tablesorter-default.pending
    %thead
      %tr
        %th= t('projects.participants.name')
        %th= t('projects.participants.address')
        %th= t('projects.participants.reports')
        %th
        %th
    - @pending_participants.each do |participant|
      %tr
        %td
          - unless participant.reports.empty?
            %span.label.label-info= t('projects.participants.is_speaker')
          = participant.user.full_name
        %td= participant.user.address
        %td
          - participant.reports.each do |report|
            = report.title
        %td= button_to t('projects.participants.approve'), approve_participant_path(participant), method: :put, class: "btn btn-small btn-success", confirm: t('projects.participants.confirm_approve')
        %td= button_to t('projects.participants.remove'), participant_path(participant), method: :delete, class: "btn btn-small btn-danger", confirm: t('projects.participants.confirm_remove')

%table.table.table-bordered.tablesorter.tablesorter-default.approved.hidden
  %thead
    %tr
      %th= t('projects.participants.name')
      %th= t('projects.participants.address')
      %th= t('projects.participants.reports')
      %th
  - @approved_participants.each do |participant|
    %tr
      %td
        - unless participant.reports.empty?
          %span.label.label-info= t('projects.participants.is_speaker')
        = participant.user.full_name
      %td= participant.user.address
      %td
        - participant.reports.each do |report|
          = report.title
      %td
        = button_to t('projects.participants.remove'), participant_path(participant), method: :delete, class: "btn btn-small btn-danger", confirm: t('projects.participants.confirm_remove')

app/views/project/participants/new.html.haml
= render partial: "form"