config/routes.rb
require "multidomain"
Confer::Application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations" }

  constraints(Multidomain) do
    scope module: "project" do
      resources :participants do
        member do
          put :approve
        end
      end
      resources :reports do
        member do
          put :approve
        end
      end
      resources :materials, only: [:index, :new, :create, :destroy] do
        member do
          put :approve
        end
      end

      resources :organizers, only: [:index, :new, :destroy, :create]
      resources :feedbacks, only: [:index, :show, :destroy, :create]

      resources :news_articles, path: "news"
      match '/feed' => 'news_items#feed',
        as: :feed,
        defaults: { format: 'atom' }

      resources :conferences, only: [:edit, :update]
      resources :pages, except: [:show]

      get "/settings" => "conferences#edit", as: :settings
      get "/contacts" => "feedbacks#new", as: :contacts

      get "/" => "projects#index"
      get "/:id" => "pages#show", as: :public_page
    end
  end

  namespace :admin do
    resources :users do
      resources :logs, only: [:index]
      member do
        put :make_admin
        put :make_user
        put :confirm
      end
    end
    resources :conferences do
      resources :logs, only: [:index]
      member do
        put :approve
      end
    end
    get "logs" => "logs#index", as: :logs
  end

  resources :users
  resources :conferences

  get "/about" => "main#about", as: :about
  root :to => 'main#index'
end

app/models/conference.rb
# == Schema Information
#
# Table name: conferences
#
#  id                :integer          not null, primary key
#  name              :string(255)
#  start_date        :datetime
#  end_date          :datetime
#  max_guests        :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  domain            :string(255)
#  registrable_until :datetime
#  state             :string(255)
#  description       :text
#  logo              :string(255)
#  theme             :string(255)
#  user_id           :integer
#  notify_email      :string(255)
#  address           :string(255)
#  phone             :string(255)
#  public_email      :string(255)
#  additional_info   :text
#  modules           :text
#

class Conference < ActiveRecord::Base
  THEMES = ["amelia.min", "cerulean.min", "cosmo.min", "cyborg.min", "journal.min", "readable.min", "salate.min", "simplex.min", "spruce.min", "superhero.min", "united.min"]
  MODULES = ["news", "reports", "participants", "contacts", "personal_page", "materials"]

  ## included modules & attr_*
  attr_accessible :end_date, :max_guests, :name, :start_date, :user_id, :domain, :registrable_until, :description, :logo, :theme, :notify_email, :address, :phone, :public_email, :additional_info, :modules
  serialize :modules, Array

  ## associations
  belongs_to :user
  has_many :participants
  has_many :guests, through: :participants, source: :user

  has_many :organizers
  has_many :stuff, through: :organizers, source: :user

  has_many :reports, dependent: :destroy
  has_many :materials, dependent: :destroy
  has_many :news_articles, dependent: :destroy

  has_many :feedbacks
  has_many :pages

  ## plugins
  audited associated_with: :user
  mount_uploader :logo, LogoUploader

  state_machine :initial => :pending do
    event :approve do
      transition :pending => :approved
    end

    after_transition :pending => :approved, :do => :notify_creator
  end

  ## callbacks
  after_create :add_owner
  after_create :force_domain_to_downcase

  ## validations
  validates :name, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :user_id, presence: true
  validates :domain, presence: true, uniqueness: true, format: { with: /^[a-zA-Z0-9-]*$/ }
  validates :notify_email, format: { with: /\A([^@\s]+)@((?:[-a-z1-9]+\.)+[a-z]{2,})\Z/i }, allow_blank: true
  validates :public_email, format: { with: /\A([^@\s]+)@((?:[-a-z1-9]+\.)+[a-z]{2,})\Z/i }, allow_blank: true
  validate :end_date_greater_than_start_date
  validate :registration_date_less_than_end_date

  ## named_scopes
  scope :future, ->(current_time) { where("end_date >= ?", current_time) }
  scope :past, ->(current_time) { where("end_date < ?", current_time) }
  scope :with_description, where("description IS NOT NULL")
  scope :random, order("RANDOM()")

  ## class methods

  public

  def module_enabled?(site_module)
    modules.include?(site_module)
  end

  def notification_email
    notify_email.present? ? notify_email : user.email
  end

  def has_guest?(user)
    !participants.where(user_id: user.id).empty?
  end

  def has_organizer?(user)
    !organizers.where(user_id: user.id).empty?
  end

  def registration_open?
    if registrable_until
      Time.now <= registrable_until && Time.now <= end_date
    else
      Time.now <= end_date
    end
  end

  def guests_limit?
    max_guests.present?
  end

  def guests_limit_reached?
    guests.count == max_guests
  end

  protected
  private

    def force_domain_to_downcase
      self.domain = domain.downcase
      save
    end

    def notify_creator
      ConferenceMailer.conference_approved(self, organizers.first).deliver
    end

    def registration_date_less_than_end_date
      if end_date.present? && registrable_until.present? && registrable_until > end_date
        errors.add(:registrable_until, I18n.t('conference.validations.registrable_until_must_be_less_or_equel_than_end_date'))
      end
    end

    def end_date_greater_than_start_date
      if start_date.present? && end_date.present? && start_date > end_date
        errors.add(:start_date, I18n.t('conference.validations.start_date_should_be_less_than_end_date'))
        errors.add(:end_date, I18n.t('conference.validations.end_date_should_be_greater_than_start_date'))
      end
    end

    def add_owner
      organizers.create!(user_id: user_id, role: "owner")
    end
end

app/controllers/admin/conferences_controller.rb
class Admin::ConferencesController < Admin::BaseController
  def index
    @conferences = Conference.order("start_date DESC")
  end

  def show
    @conference = Conference.find(params[:id])
    @audits = @conference.audits
  end

  def approve
    @conference = Conference.find(params[:id])
    @conference.approve!
    redirect_to admin_conferences_path, notice: t('admin.conferences.notices.approved')
  end

  def destroy
    Conference.find(params[:id]).destroy
    redirect_to admin_conferences_path, notice: t('admin.conferences.notices.removed')
  end

  def edit
    @conference = Conference.find(params[:id])
  end

  def update
    @conference = Conference.find(params[:id])
    @conference.update_attributes(params[:conference])
    redirect_to edit_admin_conference_path(@conference), notice: t('admin.conferences.notices.updated')
  end
end

app/controllers/conferences_controller.rb
class ConferencesController < ApplicationController
  load_and_authorize_resource

  def index
    @all_conferences = Conference.with_state(:approved).order("start_date DESC")
    @future_conferences = Conference.with_state(:approved).future(Time.now).order("start_date DESC")
    @past_conferences = Conference.with_state(:approved).past(Time.now).order("start_date DESC")
  end

  def new
    @conference = Conference.new
  end

  def show
    render :text => Conference.find(params[:id]).to_json
  end

  def create
    attrs = params[:conference].dup
    attrs[:user_id] = current_user.id
    @conference = Conference.create(attrs)
    if @conference.valid?
      redirect_to conferences_path, notice: t('conference.notices.created')
    else
      render :new
    end
  end

end

app/controllers/project/conferences_controller.rb
class Project::ConferencesController < Project::BaseProjectController
  before_filter :authorize_project_management

  def edit
  end

  def update
    @conference = Conference.find(params[:id])
    if @conference.update_attributes(params[:conference])
      redirect_to settings_path, notice: t('projects.conferences.notices.updated')
    else
      render :edit
    end
  end

end

app/helpers/conferences_helper.rb
module ConferencesHelper
  def human_date_with_time(date)
    date.strftime("%d.%m.%Y %H:%M") if date
  end

  def human_date(date)
    date.strftime("%d.%m.%Y") if date
  end

  def conference_site_link(conference, &block)
    if block
      link_to url_for(controller: :main, host: request.host, subdomain: conference.domain) do
        yield
      end
    else
      link_to conference.name, url_for(controller: :main, host: request.host, subdomain: conference.domain)
    end
  end

end

app/views/conferences/_conference.html.haml
%tr{ class: "#{!conference.registration_open? || conference.guests_limit_reached? ? 'registration-closed' : '' }" }
  %td= conference_site_link(conference)
  %td= "#{human_date(conference.start_date)} - #{human_date(conference.end_date)}"
  %td= human_date(conference.registrable_until)
  %td
    = conference.guests_limit? ? "#{conference.guests.count} / #{conference.max_guests}" : t('conference.unlimited')
  %td
    - if signed_in? && current_user.participates?(conference)
      = t('conference.you_already_participate')
    - elsif conference.registration_open? && !conference.guests_limit_reached?
      = button_to t('conference.join'), new_participant_url(subdomain: conference.domain), method: :get, class: "btn btn-primary"
    - else
      = t('conference.registration_closed')

app/views/conferences/_form.html.haml
.well
  = semantic_form_for @conference do |f|
    = f.inputs do
      = f.input :logo, label: t('conference.form.logo')
      = f.input :name, label: t('conference.form.name')
      = f.input :domain, label: t('conference.form.domain'), hint: t('conference.form.hints.domain')
      = f.input :start_date, as: :string, input_html: { class: "datepicker" }, label: t('conference.form.start_date')
      = f.input :end_date, as: :string, input_html: { class: "datepicker" }, label: t('conference.form.end_date')
      = f.input :registrable_until, as: :string, input_html: { class: "datepicker" }, label: t('conference.form.registrable_until')
      = f.input :max_guests, label: t('conference.form.max_guests')
      = f.input :description, label: t('conference.form.description')
    = f.actions do
      = f.action :submit, button_html: { class: "btn btn-success" }, label: t('conference.form.submit')

app/views/conferences/index.html.haml
- if can? :create, Conference
  .well
    %p= t("conference.new_conf_about")
    .add-conference-link
      = link_to t('conference.add'), new_conference_path, class: "btn btn-primary"

.b-conferences__nav.userspace
  %ul.nav.nav-tabs
    %li.future.active
      = link_to t("conference.nav.future"), "#", class: "future"
    %li.past
      = link_to t("conference.nav.past"), "#", class: "past"
    %li.all
      = link_to t("conference.nav.all"), "#", class: "all"

.b-conferences__list
  %table.table.table-bordered.future.tablesorter.tablesorter-default
    %thead
      %tr
        %th= t('conference.name')
        %th= t('conference.date')
        %th= t('conference.register_until')
        %th= t('conference.members_num')
        %th= t('conference.registration')
    %tbody
      = render partial: "conference", collection: @future_conferences

  %table.table.table-bordered.past.hidden
    %thead
      %tr
        %th= t('conference.name')
        %th= t('conference.date')
        %th= t('conference.register_until')
        %th= t('conference.members_num')
        %th= t('conference.registration')
    %tbody
      = render partial: "conference", collection: @past_conferences

  %table.table.table-bordered.all.hidden
    %thead
      %tr
        %th= t('conference.name')
        %th= t('conference.date')
        %th= t('conference.register_until')
        %th= t('conference.members_num')
        %th= t('conference.registration')
    %tbody
      = render partial: "conference", collection: @all_conferences

app/views/conferences/new.html.haml
%h3= t('conference.create_new')
= render :partial => "form"