config/routes.rb
require "multidomain"
Confer::Application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations" }

  constraints(Multidomain) do
    scope module: "project" do
      resources :participants do
        member do
          put :approve
        end
      end
      resources :reports do
        member do
          put :approve
        end
      end
      resources :materials, only: [:index, :new, :create, :destroy] do
        member do
          put :approve
        end
      end

      resources :organizers, only: [:index, :new, :destroy, :create]
      resources :feedbacks, only: [:index, :show, :destroy, :create]

      resources :news_articles, path: "news"
      match '/feed' => 'news_items#feed',
        as: :feed,
        defaults: { format: 'atom' }

      resources :conferences, only: [:edit, :update]
      resources :pages, except: [:show]

      get "/settings" => "conferences#edit", as: :settings
      get "/contacts" => "feedbacks#new", as: :contacts

      get "/" => "projects#index"
      get "/:id" => "pages#show", as: :public_page
    end
  end

  namespace :admin do
    resources :users do
      resources :logs, only: [:index]
      member do
        put :make_admin
        put :make_user
        put :confirm
      end
    end
    resources :conferences do
      resources :logs, only: [:index]
      member do
        put :approve
      end
    end
    get "logs" => "logs#index", as: :logs
  end

  resources :users
  resources :conferences

  get "/about" => "main#about", as: :about
  root :to => 'main#index'
end

app/controllers/admin/logs_controller.rb
class Admin::LogsController < Admin::BaseController

  def index
    @type = params[:type].present? ? params[:type] : "user"
    @audits = Audited.audit_class.where(auditable_type: @type.capitalize).order("id DESC")
  end
end

app/helpers/logs_helper.rb
module LogsHelper
  AUDIT_ACTIONS = {
    "last_sign_in_at" => "sign_in",
    "phone" => "profile_updated",
    "confirmation_token" => "confirmed",
    "service_admin" => "made_admin",
    "state" => "state_changed"
  }
  def auditable_name(audit)
    if audit.auditable.present?
      link_to auditable_title(audit.auditable), url_for([:admin, audit.auditable])
    else
      t("admin.logs.types.#{audit.auditable_type.downcase}")
    end
  end

  def auditable_title(auditable)
    if auditable.is_a? User
      auditable.email
    elsif auditable.is_a? Conference
      auditable.name
    end
  end

  def audit_actor(audit)
    link_to audit.user.email, admin_user_path(audit.user) if audit.user.present?
  end

  def audit_action(audit)
    action = audit.audited_changes.first[0]
    if AUDIT_ACTIONS[action].present?
      t("admin.logs.actions.#{audit.auditable_type.downcase}.#{AUDIT_ACTIONS[action]}")
    else
      t("admin.logs.actions.#{audit.action}")
    end
  end

end

app/views/admin/logs/index.html.haml
%h3= t('admin.logs.title')

%ul.nav.nav-tabs
  %li{class: "#{@type == 'user' ? 'active' : ''}"}
    = link_to t("admin.logs.nav.user"), admin_logs_path(type: "user")
  %li{class: "#{@type == 'conference' ? 'active' : ''}"}
    = link_to t("admin.logs.nav.conference"), admin_logs_path(type: "conference")

%table.table.table-bordered.tablesorter.tablesorter-default
  %thead
    %tr
      %th
        ID
      %th= t('admin.logs.model')
      %th= t('admin.logs.action')
      %th= t('admin.logs.actor')
      %th= t('admin.logs.date')
      %th= t('admin.logs.ip_address')
  %tbody
    - @audits.each do |audit|
      %tr
        %td= audit.id
        %td= auditable_name(audit)
        %td= audit_action(audit)
        %td= audit_actor(audit)
        %td= human_date_with_time(audit.created_at)
        %td= audit.remote_address